### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by oximer** [chkal/rocket-chat-notifier#3]
javax.net.ssl.SSLException: Certificate for <rocket-gam.labbs.com.br> doesn't match common name of the certificate subject: 201.33.152.55
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:173)
	at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:61)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:141)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:114)
	at org.apache.http.conn.ssl.SSLSocketFactory.verifyHostname(SSLSocketFactory.java:580)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:554)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)

**Comment by chkal** [comment]
Looks like a SSL problem with the server...

**Comment by oximer** [comment]
If you access the website rocket-gam.labbs.com.br, the certificate has *.labbs.com.br as common name. Thus, I don't see any issue.

**Comment by chkal** [comment]
Maybe that verifier doesn't work well with wildcard certificates? Not sure about that. I guess you have to check out the code and experiment with it yourself. I currently don't find much time to work on this any more. However, pull requests are welcome.
